import {
	ActionCard,
	Card,
	CardRarity,
	CardType,
	HubCard,
	Industry,
	Step,
} from './types';

const Cards: { [id: number]: ActionCard | HubCard } = {
	0: {
		id: 0,
		emoji: '⚠️',
		displayName: 'error',
		description: `this card does not exist anymore`,
		cardType: CardType.ACTION,
		rarity: CardRarity.COMMON,
		isTargetCard: false,
		isTargetPlayer: true,
		isTargetSelfCard: false,
	},
	10: {
		id: 10,
		emoji: '🏢',
		displayName: 'Au au',
		description: 'Limpeh go salakau fight gang lmao who u',
		cardType: CardType.ACTION,
		rarity: CardRarity.COMMON,
		isTargetCard: false,
		isTargetPlayer: true,
		isTargetSelfCard: false,
	},
	11: {
		id: 11,
		emoji: '🏢',
		displayName: 'hub11',
		description: 'test',
		cardType: CardType.HUB,
		rarity: CardRarity.COMMON,
		value: 10,
		baseIncome: 1,
		step: Step.DISTRIBUTER,
		industry: Industry.CLOTHES,
	},
	25: {
		id: 25,
		emoji: '🏢',
		displayName: 'hub25',
		description: 'test',
		cardType: CardType.HUB,
		rarity: CardRarity.COMMON,
		value: 10,
		baseIncome: 1,
		step: Step.DISTRIBUTER,
		industry: Industry.CLOTHES,
	},
};

export default Cards;
